-- models/marts/fact_matches.sql

select distinct
    match_id,
    match_date,
    city,
    gender,
    match_type,
    match_number,
    season,
    team_type,
    team_1,
    team_2,
    toss_winner,
    toss_decision,
    venue,
    winner,
    match_result,
    method,
    overs,
    player_of_match,
    player_of_match_id,
    umpire_1,
    umpire_1_id,
    umpire_2,
    umpire_2_id,
    tv_umpires,
    tv_umpires_id,
    reserve_umpires,
    reserve_umpires_id,
    match_referees,
    match_referees_id,
    event_name,
    event_stage
from {{ ref('stg_ipl_match_data') }}
