-- models/marts/fact_deliveries.sql
select
  match_id,
  innings,
  over_number,
  delivery_number,
  batter,
  bowler,
  non_striker,
  replacement_in,
  replacement_out,
  replacement_team,
  replacement_reason,
  runs_batter,
  runs_extras,
  runs_total,
  powerplay,
  wicket_kind,
  wicket_player_out,
  wicket_fielder_1,
  wicket_fielder_2,
  extras_wides,
  extras_noballs,
  extras_byes,
  extras_legbyes,
  extras_penalty,
  review_by,
  review_umpire,
  review_batter,
  review_decision,
  review_type,
  review_umpires_call,
  target_remaining,
  balls_remaining
from {{ ref('stg_ipl_match_data') }}
where match_id is not null
